Repository lunch-12/PAPERPLE-FE, pull requests merged in 2024-08, with the labels that each got.

#1 feat: 페이퍼&뉴스 UI 구현
  .eslintrc.json
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/assets/svg/FavoriteIcon.svg
  src/assets/svg/NotificationIcon.svg
  src/assets/svg/OpenInBrowserIcon.svg
  src/assets/svg/SearchIcon.svg
  src/assets/svg/SettingIcon.svg
  src/assets/svg/ShareIcon.svg
  src/components/ContentsTab.tsx
  src/components/Header.tsx
  src/components/NewsContent.tsx
  src/components/NewsFooter.tsx
  src/components/NewsHeader.tsx
  src/components/NewsItem.tsx
  src/components/NewsList.tsx
  src/components/PaperContent.tsx
  src/components/PaperFooter.tsx
  src/components/PaperHeader.tsx
  src/components/PaperItem.tsx
  src/components/PaperList.tsx
  src/components/StockBanner.tsx
  src/index.tsx
  src/pages/Home.tsx
  src/types/dto/paper/NewspaperDTO.ts
  src/types/dto/paper/PaperDTO.ts
  src/types/enums.ts
  src/utils/browserUtils.ts
  src/utils/setScreenHeight.tsx
  tailwind.config.js
  tsconfig.json
Labels: ⚙️chore, ✨feature, ✔︎pull requests

#3 feat: 페이퍼 작성 UI 구현
  src/App.tsx
  src/components/Modal.tsx
  src/components/NewsFooter.tsx
  src/components/NewsItem.tsx
  src/components/URLStatusIndicator.tsx
  src/pages/Home.tsx
  src/pages/RegisterPaper.tsx
  src/types/enums.ts
Labels: ✨feature, ✔︎pull requests

#4 페이퍼플 ver.0.0.0 (2024-08-28)
  .eslintrc.json
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/assets/svg/FavoriteIcon.svg
  src/assets/svg/NotificationIcon.svg
  src/assets/svg/OpenInBrowserIcon.svg
  src/assets/svg/SearchIcon.svg
  src/assets/svg/SettingIcon.svg
  src/assets/svg/ShareIcon.svg
  src/components/ContentsTab.tsx
  src/components/Header.tsx
  src/components/Modal.tsx
  src/components/NewsContent.tsx
  src/components/NewsFooter.tsx
  src/components/NewsHeader.tsx
  src/components/NewsItem.tsx
  src/components/NewsList.tsx
  src/components/PaperContent.tsx
  src/components/PaperFooter.tsx
  src/components/PaperHeader.tsx
  src/components/PaperItem.tsx
  src/components/PaperList.tsx
  src/components/StockBanner.tsx
  src/components/URLStatusIndicator.tsx
  src/index.tsx
  src/pages/Home.tsx
  src/pages/RegisterPaper.tsx
  src/types/dto/paper/NewspaperDTO.ts
  src/types/dto/paper/PaperDTO.ts
  src/types/enums.ts
  src/utils/browserUtils.ts
  src/utils/setScreenHeight.tsx
  tailwind.config.js
  tsconfig.json
Labels: release

#2 feat: 로그인 팝업 UI
  package-lock.json
  package.json
  src/App.tsx
  src/assets/png/KakaoLoginIcon.png
  src/assets/svg/LogoIcon.svg
  src/components/Header.tsx
  src/components/LoginModal.tsx
  src/components/NewsContent.tsx
  src/components/NewsFooter.tsx
  src/components/NewsItem.tsx
  src/config.ts
  src/pages/HomePage.tsx
  src/stores/useAuthStore.tsx
  src/types/dto/user/UserDTO.ts
  tailwind.config.js
Labels: ✨feature, ✔︎pull requests
