Repository lunch-12/PAPERPLE-FE, pull requests merged in 2024-09, with the labels that each got.

#7 feat: 검색 UI 구현
  src/App.tsx
  src/components/Header.tsx
  src/components/Search.tsx
  src/pages/SearchPage.tsx
Labels: ✨feature, ✔︎pull requests, 🪄refactor

#13 feat: logout
  src/App.tsx
  src/pages/UserPage.tsx
Labels: ✨feature

#17 feat: 뉴스 인용 시 url 미리 등록
  src/components/NewsFooter.tsx
  src/components/NewsItem.tsx
Labels: ✨feature

#19 [FEAT/#25] 페이퍼 리스트 출력
  src/components/PaperList.tsx
  src/pages/HomePage.tsx
Labels: ✨feature, ✔︎pull requests
